= Distributed system homework
:figure-caption!:

== Architecture Diagram

[#img-architecture, link=./docs/Images/Architecture_diagram.svg]
image::./docs/Images/Architecture_diagram.svg[Architecture Diagram]

The orangesh brown components represent components that are only connected to
the internal network, which means that they are only accessable from the internal
"docker" network. This is done because we want to minimize the possible attack
surface. 

== Sequence diagrams

.Website loading flow
image::./docs/Images/Sequence_get_website.svg.svg[Checkout flow]

The image is the sequence diagram how the website loads. It does not say 
explicitly which functions are called only which microservices are called. 

.Checkout flow
image::./docs/Images/Sequence_checkout.svg[Checkout flow]

The image is the sequence diagram of the checkout process. The orchestrator
initaties multiple connections in the same time, because it uses coroutines, so
it can run code while it waits for the responses of the microservices.

