"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ClearMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: _builtins.int
    VECTOR_CLOCK_FIELD_NUMBER: _builtins.int
    order_id: _builtins.str
    @_builtins.property
    def vector_clock(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        order_id: _builtins.str = ...,
        vector_clock: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["order_id", b"order_id", "vector_clock", b"vector_clock"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ClearMessage: _TypeAlias = ClearMessage  # noqa: Y015

@_typing.final
class VC(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VECTOR_CLOCK_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def vector_clock(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        vector_clock: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["vector_clock", b"vector_clock"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VC: _TypeAlias = VC  # noqa: Y015

@_typing.final
class Message(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: _builtins.int
    VECTOR_CLOCK_FIELD_NUMBER: _builtins.int
    order_id: _builtins.str
    @_builtins.property
    def vector_clock(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        order_id: _builtins.str = ...,
        vector_clock: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["order_id", b"order_id", "vector_clock", b"vector_clock"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Message: _TypeAlias = Message  # noqa: Y015

@_typing.final
class Empty(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___Empty: _TypeAlias = Empty  # noqa: Y015
