# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\"m\n\x0c\x46raudRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\n\n\x02vc\x18\x02 \x03(\x05\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x14\n\x0corder_amount\x18\x04 \x01(\x05\x12\x17\n\x0f\x62illing_address\x18\x05 \x01(\t\"\x1a\n\x0c\x63ompletionVC\x12\n\n\x02vc\x18\x01 \x03(\x05\"1\n\rFraudResponse\x12\x0e\n\x06\x66\x61iled\x18\x01 \x01(\x08\x12\x10\n\x08is_fraud\x18\x02 \x01(\x08\"\x07\n\x05\x45mpty2g\n\x19\x46raudDetectionServiceInit\x12J\n\nCheckFraud\x12\x1d.fraud_detection.FraudRequest\x1a\x1d.fraud_detection.completionVC2c\n\x1d\x46raudDetectionServiceFinished\x12\x42\n\x08Response\x12\x1e.fraud_detection.FraudResponse\x1a\x16.fraud_detection.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAUDREQUEST']._serialized_start=42
  _globals['_FRAUDREQUEST']._serialized_end=151
  _globals['_COMPLETIONVC']._serialized_start=153
  _globals['_COMPLETIONVC']._serialized_end=179
  _globals['_FRAUDRESPONSE']._serialized_start=181
  _globals['_FRAUDRESPONSE']._serialized_end=230
  _globals['_EMPTY']._serialized_start=232
  _globals['_EMPTY']._serialized_end=239
  _globals['_FRAUDDETECTIONSERVICEINIT']._serialized_start=241
  _globals['_FRAUDDETECTIONSERVICEINIT']._serialized_end=344
  _globals['_FRAUDDETECTIONSERVICEFINISHED']._serialized_start=346
  _globals['_FRAUDDETECTIONSERVICEFINISHED']._serialized_end=445
# @@protoc_insertion_point(module_scope)
