"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PrepareRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    amount: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        amount: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PrepareRequest: _TypeAlias = PrepareRequest  # noqa: Y015

@_typing.final
class PrepareResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    READY_FIELD_NUMBER: _builtins.int
    ready: _builtins.bool
    def __init__(
        self,
        *,
        ready: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ready", b"ready"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PrepareResponse: _TypeAlias = PrepareResponse  # noqa: Y015

@_typing.final
class CommitRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    order_id: _builtins.str
    title: _builtins.str
    def __init__(
        self,
        *,
        order_id: _builtins.str = ...,
        title: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["order_id", b"order_id", "title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CommitRequest: _TypeAlias = CommitRequest  # noqa: Y015

@_typing.final
class CommitResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CommitResponse: _TypeAlias = CommitResponse  # noqa: Y015

@_typing.final
class AbortRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: _builtins.int
    order_id: _builtins.str
    def __init__(
        self,
        *,
        order_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["order_id", b"order_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AbortRequest: _TypeAlias = AbortRequest  # noqa: Y015

@_typing.final
class AbortResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ABORTED_FIELD_NUMBER: _builtins.int
    aborted: _builtins.bool
    def __init__(
        self,
        *,
        aborted: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aborted", b"aborted"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AbortResponse: _TypeAlias = AbortResponse  # noqa: Y015
