# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: commitment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'commitment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ommitment.proto\x12\x07payment\",\n\x0ePrepareRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\" \n\x0fPrepareResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\"0\n\rCommitRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\"!\n\x0e\x43ommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\x0c\x41\x62ortRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\" \n\rAbortResponse\x12\x0f\n\x07\x61\x62orted\x18\x01 \x01(\x08\x32\xc3\x01\n\x10\x43ommitmentScheme\x12<\n\x07Prepare\x12\x17.payment.PrepareRequest\x1a\x18.payment.PrepareResponse\x12\x39\n\x06\x43ommit\x12\x16.payment.CommitRequest\x1a\x17.payment.CommitResponse\x12\x36\n\x05\x41\x62ort\x12\x15.payment.AbortRequest\x1a\x16.payment.AbortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commitment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREPAREREQUEST']._serialized_start=29
  _globals['_PREPAREREQUEST']._serialized_end=73
  _globals['_PREPARERESPONSE']._serialized_start=75
  _globals['_PREPARERESPONSE']._serialized_end=107
  _globals['_COMMITREQUEST']._serialized_start=109
  _globals['_COMMITREQUEST']._serialized_end=157
  _globals['_COMMITRESPONSE']._serialized_start=159
  _globals['_COMMITRESPONSE']._serialized_end=192
  _globals['_ABORTREQUEST']._serialized_start=194
  _globals['_ABORTREQUEST']._serialized_end=226
  _globals['_ABORTRESPONSE']._serialized_start=228
  _globals['_ABORTRESPONSE']._serialized_end=260
  _globals['_COMMITMENTSCHEME']._serialized_start=263
  _globals['_COMMITMENTSCHEME']._serialized_end=458
# @@protoc_insertion_point(module_scope)
