"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ReadRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TITLE_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    def __init__(
        self,
        *,
        title: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ReadRequest: _TypeAlias = ReadRequest  # noqa: Y015

@_typing.final
class ReadResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STOCK_FIELD_NUMBER: _builtins.int
    stock: _builtins.int
    def __init__(
        self,
        *,
        stock: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stock", b"stock"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ReadResponse: _TypeAlias = ReadResponse  # noqa: Y015

@_typing.final
class WriteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TITILE_FIELD_NUMBER: _builtins.int
    NEW_STOCK_FIELD_NUMBER: _builtins.int
    titile: _builtins.str
    new_stock: _builtins.int
    def __init__(
        self,
        *,
        titile: _builtins.str = ...,
        new_stock: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["new_stock", b"new_stock", "titile", b"titile"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WriteRequest: _TypeAlias = WriteRequest  # noqa: Y015

@_typing.final
class WriteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WriteResponse: _TypeAlias = WriteResponse  # noqa: Y015
