"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ReadRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TITLE_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    def __init__(
        self,
        *,
        title: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ReadRequest: _TypeAlias = ReadRequest  # noqa: Y015

@_typing.final
class ReadResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STOCK_FIELD_NUMBER: _builtins.int
    stock: _builtins.int
    def __init__(
        self,
        *,
        stock: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stock", b"stock"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ReadResponse: _TypeAlias = ReadResponse  # noqa: Y015

@_typing.final
class ReadAllRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ReadAllRequest: _TypeAlias = ReadAllRequest  # noqa: Y015

@_typing.final
class ReadAllResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class StockListEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.int
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.int = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    STOCK_LIST_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stock_list(self) -> _containers.ScalarMap[_builtins.str, _builtins.int]: ...
    def __init__(
        self,
        *,
        stock_list: _abc.Mapping[_builtins.str, _builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stock_list", b"stock_list"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ReadAllResponse: _TypeAlias = ReadAllResponse  # noqa: Y015

@_typing.final
class WriteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TITLE_FIELD_NUMBER: _builtins.int
    NEW_STOCK_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    new_stock: _builtins.int
    def __init__(
        self,
        *,
        title: _builtins.str = ...,
        new_stock: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["new_stock", b"new_stock", "title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WriteRequest: _TypeAlias = WriteRequest  # noqa: Y015

@_typing.final
class WriteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WriteResponse: _TypeAlias = WriteResponse  # noqa: Y015

@_typing.final
class PrepareWriteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___PrepareWriteRequest: _TypeAlias = PrepareWriteRequest  # noqa: Y015

@_typing.final
class PrepareWriteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___PrepareWriteResponse: _TypeAlias = PrepareWriteResponse  # noqa: Y015
