"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class EnqueueRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: _builtins.int
    order_id: _builtins.str
    def __init__(
        self,
        *,
        order_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["order_id", b"order_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EnqueueRequest: _TypeAlias = EnqueueRequest  # noqa: Y015

@_typing.final
class EnqueueResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EnqueueResponse: _TypeAlias = EnqueueResponse  # noqa: Y015

@_typing.final
class DequeueRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DequeueRequest: _TypeAlias = DequeueRequest  # noqa: Y015

@_typing.final
class DequeueResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: _builtins.int
    order_id: _builtins.str
    def __init__(
        self,
        *,
        order_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["order_id", b"order_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DequeueResponse: _TypeAlias = DequeueResponse  # noqa: Y015
