# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bullying.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bullying.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62ullying.proto\x12\x08\x62ullying\"\x06\n\x04Pong\"\x06\n\x04Ping2?\n\x10HeartbeatService\x12+\n\tHeartbeat\x12\x0e.bullying.Ping\x1a\x0e.bullying.Pong27\n\x08\x45lection\x12+\n\tHeartbeat\x12\x0e.bullying.Ping\x1a\x0e.bullying.Pong2:\n\x0b\x43oordinator\x12+\n\tHeartbeat\x12\x0e.bullying.Ping\x1a\x0e.bullying.Pongb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bullying_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PONG']._serialized_start=28
  _globals['_PONG']._serialized_end=34
  _globals['_PING']._serialized_start=36
  _globals['_PING']._serialized_end=42
  _globals['_HEARTBEATSERVICE']._serialized_start=44
  _globals['_HEARTBEATSERVICE']._serialized_end=107
  _globals['_ELECTION']._serialized_start=109
  _globals['_ELECTION']._serialized_end=164
  _globals['_COORDINATOR']._serialized_start=166
  _globals['_COORDINATOR']._serialized_end=224
# @@protoc_insertion_point(module_scope)
